# SPDX-FileCopyrightText: Contributors to atlite <https://github.com/pypsa/atlite>
#
# SPDX-License-Identifier: CC0-1.0
blank_issues_enabled: false
contact_links:
- name: PyPSA Mailing List
  url: https://groups.google.com/forum/#!forum/pypsa
  about: Please use the PyPSA mailing list for general questions regarding the usage.
- name: Stackoverflow
  url: https://stackoverflow.com/questions/tagged/pypsa
  about: Please ask and answer code-related questions here.
