# SPDX-FileCopyrightText: Contributors to atlite <https://github.com/pypsa/atlite>
#
# SPDX-License-Identifier: MIT
name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: "0 1 * * *"
  workflow_dispatch:
    inputs:
      cache_cutouts:
        description: "Cache cutouts for all Python versions"
        default: "false"
        required: true
  workflow_call:

# Cancel any in-progress runs when a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # Build the Python SDist and wheel, performs metadata and readme linting
    name: Build and verify package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0   # Needed for setuptools_scm
    - uses: hynek/build-and-inspect-python-package@v2
      id: baipp

    outputs:
      python-versions: ${{ steps.baipp.outputs.supported_python_classifiers_json_array }}

  test:
    # Test package build in matrix of OS and Python versions
    name: Test package
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Only run ubuntu/3.12 on scheduled runs to create cache
        python-version: ${{ fromJSON(github.event_name == 'schedule' && '["3.12"]' || needs.build.outputs.python-versions) }}
        os: ${{ fromJSON(github.event_name == 'schedule' && '["ubuntu-latest"]' || '["ubuntu-latest","macos-latest","windows-latest"]') }}
    env:
      MPLBACKEND: Agg  # https://github.com/orgs/community/discussions/26434
      CDSAPI_URL: ${{ vars.CDSAPI_URL }}
      CDSAPI_KEY: ${{ secrets.CDSAPI_TOKEN }}

    steps:
    - name: Setup cache and secrets (Linux & MacOS)
      if: runner.os != 'Windows'
      run: |
        echo "CACHE_PATH=$HOME/.atlite_cache" >> $GITHUB_ENV
        echo "today=$(date +'%Y-%m-%d')"  >> $GITHUB_ENV
      shell: bash

    - name: Setup cache and secrets (Windows)
      if: runner.os == 'Windows'
      run: |
        echo CACHE_PATH=%USERPROFILE%\.atlite_cache >> %GITHUB_ENV%
        for /f "tokens=2 delims==" %%a in ('"wmic os get localdatetime /value"') do set "today=%%a"
        set mydate=%today:~0,4%-%today:~4,2%-%today:~6,2%
        echo today=%mydate% >> %GITHUB_ENV%
      shell: cmd

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Needed for setuptools_scm

    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache retrieved cutouts
      if: ${{ inputs.cache_cutouts != 'false' }}
      uses: actions/cache@v4
      with:
        path: ${{ env.CACHE_PATH }}
        key: retrieved-cutouts-${{ env.today }}
        enableCrossOsArchive: true

    - name: Download package
      uses: actions/download-artifact@v4
      with:
        name: Packages
        path: dist

    - name: Install package and dependencies
      run: |
        python -m pip install uv
        uv pip install --compile --system "$(ls dist/*.whl)[dev]"

    - name: Test with pytest
      if: matrix.os != 'windows-latest' || matrix.python-version != '3.13'
      run: |
        coverage run -m pytest . --cache-path=${{ env.CACHE_PATH }} --verbose
        coverage xml

    - name: Test with pytest (windows & Python 3.13)
      if: matrix.os == 'windows-latest' && matrix.python-version == '3.13'
      run: |
        coverage run -m pytest . --cache-path=${{ env.CACHE_PATH }} --verbose
        coverage xml
        return 0 # Ignore windows and pytest 3.13

    - name: Upload code coverage report
      if: github.event_name != 'schedule'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
